-- Row Level Security policies for Supabase.
-- Not generated by drizzle-kit (RLS isn't part of the Drizzle schema model) —
-- apply manually via the Supabase SQL editor or `psql -f`, after 0000/0001.
--
-- The API server's service_role client bypasses RLS entirely for both reads
-- and writes, so these policies are defense-in-depth for the anon/authenticated
-- roles only (relevant if anything is ever queried directly from the browser).

ALTER TABLE "vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "updates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "news_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "news_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ingestion_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ingestion_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_likes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_id_mapping" ENABLE ROW LEVEL SECURITY;

-- Public read-only feed data.
CREATE POLICY "public_read" ON "vendors" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "categories" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "updates" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "news_items" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "news_sources" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "ingestion_sources" FOR SELECT TO anon, authenticated USING (true);

-- Everything else (ingestion_runs, user_preferences, user_likes, api_keys,
-- user_id_mapping): no anon/authenticated policies at all — default-deny.
-- Only the service_role client (used by the API server and GitHub Actions
-- ingestion job) can read or write these.
