-- Row Level Security policies for the tables added in 0003_square_umar.
-- Not generated by drizzle-kit (RLS isn't part of the Drizzle schema model) --
-- apply manually via the Supabase SQL editor or `psql -f`, after 0003.
--
-- Same rationale as 0002_rls_policies.sql: the API server connects as a role
-- that bypasses RLS, so these are defence-in-depth for anon/authenticated only.
--
-- Both tables are public read: they carry no user data, only the mapping from
-- classifier strings to vendors and the resolved attribution.

ALTER TABLE "vendor_aliases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "news_item_vendors" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_read" ON "vendor_aliases" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "news_item_vendors" FOR SELECT TO anon, authenticated USING (true);
